name: Update flake inputs

on:
  schedule:
    - cron: "0 12 ? * TUE"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-inputs:
    name: Update inputs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: nix flake update --commit-lock-file
      - run: nix flake check --all-systems
      - run: nix eval .#tests
      - run: |
          nix flake check ./templates/basic --all-systems \
            --override-input flakelight-darwin .
      - run: |
          nix flake check ./templates/autoload --all-systems \
            --override-input flakelight-darwin .
      - run: git push
